pipeline{
    agent {label 'ansible'}
    stages{
        stage(clonningthe repo){
            git url: 'https://github.com/kishorebittu3003/documents.git',branch:'integration_ansible_jenkin
        }
        stage('clonning'){
            steps{
                sh"""
                    cd integration_ansible_jenkins/ 
                    ansibile -i devhosts -m ping all
                    ansible-playbook -i devhosts playbook
                  """
            }
        }
    }
}
